# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Belajar GNU/Linux Indonesia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ini adalah situs resmi komunitas Belajar GNU/Linux Indonesia di Telegram
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: bgli
github_username:  bgli

# Build settings
markdown: kramdown
